name: release ci-cd

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
          release-type: simple

      - name: Update alias
        if: ${{ steps.release.outputs.release_created == 'true' }}
        run: |
          MAJOR=v${{ steps.release.outputs.major }}
          git tag -f $MAJOR
          git push origin $MAJOR --force
