name: build and deploy game

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      domain:
        description: domain name
        required: true
        type: string
      game_name:
        description: Custom game name for URL
        required: false
        type: string
        default: ''
      build_soc:
        description: 'Build SOC version?'
        required: false
        type: boolean
        default: false

env:
  GITHUB_AUTH_TOKEN: ${{ secrets.PACKAGES_TOKEN }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check deploy permissions
        if: ${{ inputs.environment == 'prod' }}
        run: |
          ALLOWED_USERS="${{ secrets.PROD_DEPLOY_USERS }}"
          IFS=',' read -ra USERS <<< "$ALLOWED_USERS"

          IS_ALLOWED=false

          for USER in "${USERS[@]}"; do
            if [[ "$USER" == "${{ github.actor }}" ]]; then
              IS_ALLOWED=true
              break
            fi
          done

          if [[ "$IS_ALLOWED" != "true" ]]; then
            echo "User '${{ github.actor }}' is not allowed to deploy to production"
            exit 1
          fi

      - uses: actions/checkout@v4
        with:
          lfs: true
          fetch-depth: 0

      - uses: playbro-games/ci-cd/.github/actions/pnpm-install@v1

      - uses: playbro-games/ci-cd/.github/actions/pnpm-assets@v1

      - name: Set GAME_NAME if not set
        run: |
          GAME_NAME_INPUT="${{ inputs.game_name }}"
          if [ -z "$GAME_NAME_INPUT" ]; then
            GAME_NAME_INPUT="${{ github.event.repository.name }}"
          fi
          echo "GAME_NAME=$GAME_NAME_INPUT" >> $GITHUB_ENV
        shell: bash

      - name: Set normalized DOMAIN
        run: |
          DOMAIN_INPUT="${{ inputs.domain }}"
          echo "DOMAIN=${DOMAIN_INPUT%/}" >> $GITHUB_ENV
        shell: bash

      - name: Set GAME_VERSION
        run: |
          if [[ "${GITHUB_REF_TYPE}" != "tag" ]]; then
            echo "This workflow can run only on tags"
            exit 1
          fi
          echo "GAME_VERSION=${GITHUB_REF_NAME}" >> $GITHUB_ENV

      - name: Build and Upload SOC
        if: ${{ inputs.build_soc }}
        run: |
          pnpm build
          zip -r dist.zip dist
          curl -fT dist.zip \
            -H "X-Environment: ${{ inputs.environment }}" \
            -H "X-Game-Version: ${{ env.GAME_VERSION }}" \
            -H "X-Notify: false" \
            "${{ env.DOMAIN }}/soc_${{ env.GAME_NAME }}.zip"
          rm -rf dist.zip dist
        env:
          VITE_TOOLS: ${{ inputs.environment == 'dev' }}
          VITE_SOC: true

      - name: Build and Upload Game
        run: |
          pnpm build
          zip -r dist.zip dist
          curl -fT dist.zip \
            -H "X-Environment: ${{ inputs.environment }}" \
            -H "X-Game-Version: ${{ env.GAME_VERSION }}" \
            -H "X-Notify: true" \
            "${{ env.DOMAIN }}/${{ env.GAME_NAME }}.zip"
        env:
          VITE_TOOLS: ${{ inputs.environment == 'dev' }}

      - name: Enable Cloudflare Development Mode
        run: |
          curl -X PATCH "https://api.cloudflare.com/client/v4/zones/d4e632db0b523f3d936a15f0077ec872/settings/development_mode" \
            -H "Authorization: Bearer ${{ secrets.CF_API_TOKEN }}" \
            -H "Content-Type: application/json" \
            --data '{"value":"on"}'
