name: pnpm-publish

on:
  workflow_call:

env:
  PLAYBRO_REGISTRY: https://npm.pkg.github.com
  GITHUB_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  publish:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: playbro-tech/ci-cd/.github/actions/pnpm-install@v1
      - run: pnpm build
      - run: pnpm publish --no-git-checks --access public
