name: Validate

on:
  workflow_call:

env:
  GITHUB_AUTH_TOKEN: ${{ secrets.PACKAGES_TOKEN }}

jobs:
  changes-check:
    runs-on: ubuntu-latest
    outputs:
      src: ${{ steps.changes-check.outputs.src }}
      deps: ${{ steps.changes-check.outputs.deps }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: changes-check
        with:
          filters: |
            src:
              - 'src/**'
            deps:
              - 'pnpm-lock.yaml'

  validate:
    needs: changes-check
    if: ${{ needs.changes-check.outputs.src == 'true' || needs.changes-check.outputs.deps == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: playbro-games/ci-cd/.github/actions/pnpm-install@v1
      - run: pnpm lint
