name: pnpm-publish

on:
  workflow_call:

env:
  GITHUB_AUTH_TOKEN: ${{ secrets.PACKAGES_TOKEN }}
  
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: playbro-games/ci-cd/.github/actions/pnpm-install@v1
      - run: pnpm build
      - run: pnpm publish --no-git-checks --access public
